<?php

namespace ShopAgg\AI_Deployer\Infrastructure;

final class Runtime {

    public static function defaultDataDir(): string {
        $configured = getenv('SHOPAGG_AI_DEPLOYER_DATA_DIR');
        if (is_string($configured) && trim($configured) !== '') {
            return rtrim($configured, '/\\');
        }
        return rtrim(WP_CONTENT_DIR, '/\\') . '/.shopagg-ai-deployer';
    }

    public static function ensure(string $siteUrl = ''): void {
        $dataDir = defined('SHOPAGG_AI_DEPLOYER_DATA_DIR')
            ? SHOPAGG_AI_DEPLOYER_DATA_DIR
            : self::defaultDataDir();

        foreach ([$dataDir, $dataDir . '/backups', $dataDir . '/operations', $dataDir . '/logs'] as $directory) {
            if (!is_dir($directory)) {
                wp_mkdir_p($directory);
            }
            @chmod($directory, 0700);
        }

        self::protect($dataDir);
        foreach (['/deployment.lock', '/extensions.lock', '/logs/activity.jsonl', '/logs/recovery.jsonl'] as $runtimeFile) {
            if (is_file($dataDir . $runtimeFile)) {
                @chmod($dataDir . $runtimeFile, 0600);
            }
        }
        self::ensureCredentials($siteUrl);
        self::migrateBackups($dataDir . '/backups');
        self::removeMigratedLegacyCredential();
    }

    public static function credential(string $name): string {
        $credentials = self::readCredentials();
        return isset($credentials[$name]) && is_string($credentials[$name])
            ? $credentials[$name]
            : '';
    }

    public static function rotateCredential(string $name): string {
        if ($name !== 'api_key') {
            return '';
        }
        $credentials = self::readCredentials();
        $credentials[$name] = self::generateToken();
        $credentials['rotated_at'] = gmdate('c');
        return self::writeCredentials($credentials) ? $credentials[$name] : '';
    }

    public static function readCredentials(): array {
        $file = defined('SHOPAGG_AI_DEPLOYER_CONFIG_FILE')
            ? SHOPAGG_AI_DEPLOYER_CONFIG_FILE
            : self::defaultDataDir() . '/credentials.php';
        if (!is_file($file)) {
            return [];
        }
        $value = include $file;
        return is_array($value) ? $value : [];
    }

    public static function writeCredentials(array $credentials): bool {
        $file = defined('SHOPAGG_AI_DEPLOYER_CONFIG_FILE')
            ? SHOPAGG_AI_DEPLOYER_CONFIG_FILE
            : self::defaultDataDir() . '/credentials.php';
        $directory = dirname($file);
        if (!is_dir($directory) && !wp_mkdir_p($directory)) {
            return false;
        }
        $content = "<?php\n// Generated by SHOPAGG AI Deployer. Do not expose this file.\nreturn "
            . var_export($credentials, true) . ";\n";
        $temporary = @tempnam($directory, '.shopagg-credentials-');
        if ($temporary === false || @file_put_contents($temporary, $content, LOCK_EX) === false) {
            if ($temporary) {
                @unlink($temporary);
            }
            return false;
        }
        @chmod($temporary, 0600);
        if (!@rename($temporary, $file)) {
            @unlink($temporary);
            return false;
        }
        return true;
    }

    private static function ensureCredentials(string $siteUrl): void {
        $credentials = self::readCredentials();
        if (!$credentials) {
            $credentials = [
                'api_key' => self::generateToken(),
                'site_url' => $siteUrl,
                'created_at' => gmdate('c'),
            ];
            self::writeCredentials($credentials);
            return;
        }

        $changed = false;
        if (empty($credentials['api_key'])) {
            $credentials['api_key'] = self::generateToken();
            $changed = true;
        }
        foreach (['legacy_api_key', 'recovery_key'] as $obsoleteCredential) {
            if (array_key_exists($obsoleteCredential, $credentials)) {
                unset($credentials[$obsoleteCredential]);
                $changed = true;
            }
        }
        if ($siteUrl !== '' && ($credentials['site_url'] ?? '') !== $siteUrl) {
            $credentials['site_url'] = $siteUrl;
            $changed = true;
        }
        if ($changed) {
            self::writeCredentials($credentials);
        }
    }

    private static function protect(string $directory): void {
        $rules = "Options -Indexes\n<IfModule mod_authz_core.c>\nRequire all denied\n</IfModule>\n"
            . "<IfModule !mod_authz_core.c>\nDeny from all\n</IfModule>\n";
        @file_put_contents($directory . '/.htaccess', $rules, LOCK_EX);
        @file_put_contents(
            $directory . '/web.config',
            '<?xml version="1.0" encoding="UTF-8"?><configuration><system.webServer><authorization>'
            . '<remove users="*" roles="" verbs="" /><add accessType="Deny" users="*" />'
            . '</authorization></system.webServer></configuration>',
            LOCK_EX
        );
        if (!is_file($directory . '/index.php')) {
            @file_put_contents($directory . '/index.php', "<?php\nhttp_response_code(404);\nexit;\n", LOCK_EX);
            @chmod($directory . '/index.php', 0600);
        }
        foreach (['/.htaccess', '/web.config', '/index.php'] as $protectedFile) {
            @chmod($directory . $protectedFile, 0600);
        }
    }

    private static function generateToken(): string {
        try {
            return substr(bin2hex(random_bytes(32)), 0, 48);
        } catch (\Throwable $error) {
            return substr(hash('sha256', uniqid('shopagg', true) . microtime(true)), 0, 48);
        }
    }

    private static function migrateBackups(string $destination): void {
        $legacy = SHOPAGG_AI_DEPLOYER_DIR . 'backups';
        if (!is_dir($legacy) || realpath($legacy) === realpath($destination)) {
            return;
        }
        $snapshots = glob($legacy . '/*', GLOB_ONLYDIR) ?: [];
        foreach ($snapshots as $snapshot) {
            $target = $destination . '/' . basename($snapshot);
            if (!file_exists($target)) {
                self::copyDirectory($snapshot, $target);
            }
        }
    }

    private static function removeMigratedLegacyCredential(): void {
        $legacy = SHOPAGG_AI_DEPLOYER_DIR . 'includes/config.php';
        $current = defined('SHOPAGG_AI_DEPLOYER_CONFIG_FILE')
            ? SHOPAGG_AI_DEPLOYER_CONFIG_FILE
            : self::defaultDataDir() . '/credentials.php';
        if (is_file($legacy) && is_file($current) && realpath($legacy) !== realpath($current)) {
            @unlink($legacy);
        }
    }

    private static function copyDirectory(string $source, string $destination): void {
        if (!is_dir($destination) && !@mkdir($destination, 0700, true)) {
            return;
        }
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($source, \RecursiveDirectoryIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::SELF_FIRST
        );
        foreach ($iterator as $item) {
            $relative = substr($item->getPathname(), strlen($source) + 1);
            $target = $destination . '/' . $relative;
            if ($item->isDir()) {
                if (!is_dir($target)) {
                    @mkdir($target, 0700, true);
                }
            } elseif ($item->isFile()) {
                @copy($item->getPathname(), $target);
                @chmod($target, 0600);
            }
        }
    }
}
