<?php
/**
 * Plugin Name: SHOPAGG AI Deployer
 * Plugin URI:  https://www.shopagg.com/
 * Description: Secure AI-assisted WordPress development with authenticated APIs, automatic backups, health checks, audit history, and an independent recovery channel.
 * Version:     1.2.1
 * Author:      庄朋龙
 * Author URI:  https://zhuangpenglong.com/
 * License:     GPL-2.0+
 * Text Domain: shopagg-ai-deployer
 *
 * @package SHOPAGG_AI_Deployer
 */

defined('ABSPATH') || exit;

define('SHOPAGG_AI_DEPLOYER_VERSION', '1.2.1');
define('SHOPAGG_AI_DEPLOYER_DIR', plugin_dir_path(__FILE__));
define('SHOPAGG_AI_DEPLOYER_URL', plugin_dir_url(__FILE__));
define('SHOPAGG_AI_DEPLOYER_BACKUP_DIR', SHOPAGG_AI_DEPLOYER_DIR . 'backups');
define('SHOPAGG_AI_DEPLOYER_CONFIG_FILE', SHOPAGG_AI_DEPLOYER_DIR . 'includes/config.php');
define('SHOPAGG_AI_DEPLOYER_REST_NS', 'shopagg-ai-deployer/v1');

register_activation_hook(__FILE__, 'shopagg_ai_deployer_activate');

function shopagg_ai_deployer_activate(): void {
    shopagg_ai_deployer_ensure_runtime_files();
    update_option('shopagg_ai_deployer_version', SHOPAGG_AI_DEPLOYER_VERSION, false);
}

function shopagg_ai_deployer_ensure_runtime_files(): void {
    shopagg_ai_deployer_ensure_config();
    shopagg_ai_deployer_ensure_backup_dir();
    shopagg_ai_deployer_protect_internal_directories();
}

function shopagg_ai_deployer_maybe_upgrade(): void {
    $installed = (string) get_option('shopagg_ai_deployer_version', '');
    if ($installed !== SHOPAGG_AI_DEPLOYER_VERSION) {
        shopagg_ai_deployer_ensure_runtime_files();
        update_option('shopagg_ai_deployer_version', SHOPAGG_AI_DEPLOYER_VERSION, false);
        return;
    }
    if (!is_file(SHOPAGG_AI_DEPLOYER_CONFIG_FILE)) {
        shopagg_ai_deployer_ensure_config();
    }
}

function shopagg_ai_deployer_ensure_config(): void {
    if (is_file(SHOPAGG_AI_DEPLOYER_CONFIG_FILE)) {
        return;
    }
    shopagg_ai_deployer_write_key_file(wp_generate_password(48, false, false));
}

function shopagg_ai_deployer_write_key_file(string $key): bool {
    $directory = dirname(SHOPAGG_AI_DEPLOYER_CONFIG_FILE);
    if (!is_dir($directory) && !wp_mkdir_p($directory)) {
        return false;
    }
    $content = "<?php\n// Auto-generated by SHOPAGG AI Deployer. Never expose this file.\n"
        . "return '" . addcslashes($key, "'\\") . "';\n";
    $temporary = @tempnam($directory, '.shopagg-key-');
    if ($temporary === false || @file_put_contents($temporary, $content, LOCK_EX) === false) {
        if ($temporary) {
            @unlink($temporary);
        }
        return false;
    }
    @chmod($temporary, 0600);
    if (!@rename($temporary, SHOPAGG_AI_DEPLOYER_CONFIG_FILE)) {
        @unlink($temporary);
        return false;
    }
    return true;
}

function shopagg_ai_deployer_get_api_key(): string {
    if (!is_file(SHOPAGG_AI_DEPLOYER_CONFIG_FILE)) {
        return '';
    }
    $key = include SHOPAGG_AI_DEPLOYER_CONFIG_FILE;
    return is_string($key) ? $key : '';
}

function shopagg_ai_deployer_regenerate_api_key(): string {
    $key = wp_generate_password(48, false, false);
    return shopagg_ai_deployer_write_key_file($key) ? $key : '';
}

function shopagg_ai_deployer_ensure_backup_dir(): void {
    if (!is_dir(SHOPAGG_AI_DEPLOYER_BACKUP_DIR)) {
        wp_mkdir_p(SHOPAGG_AI_DEPLOYER_BACKUP_DIR);
    }
    $index = SHOPAGG_AI_DEPLOYER_BACKUP_DIR . '/index.php';
    if (!is_file($index)) {
        @file_put_contents($index, "<?php\nhttp_response_code(404);\nexit;\n", LOCK_EX);
    }
}

function shopagg_ai_deployer_protect_internal_directories(): void {
    $rules = "Options -Indexes\n"
        . "<IfModule mod_authz_core.c>\nRequire all denied\n</IfModule>\n"
        . "<IfModule !mod_authz_core.c>\nDeny from all\n</IfModule>\n";

    foreach ([SHOPAGG_AI_DEPLOYER_BACKUP_DIR, SHOPAGG_AI_DEPLOYER_DIR . 'includes'] as $directory) {
        if (is_dir($directory)) {
            @file_put_contents($directory . '/.htaccess', $rules, LOCK_EX);
            $web_config = '<?xml version="1.0" encoding="UTF-8"?>'
                . '<configuration><system.webServer><authorization>'
                . '<remove users="*" roles="" verbs="" />'
                . '<add accessType="Deny" users="*" />'
                . '</authorization></system.webServer></configuration>';
            @file_put_contents($directory . '/web.config', $web_config, LOCK_EX);
        }
    }
}

require_once SHOPAGG_AI_DEPLOYER_DIR . 'includes/class-api.php';
require_once SHOPAGG_AI_DEPLOYER_DIR . 'includes/class-admin.php';

shopagg_ai_deployer_maybe_upgrade();
shopagg_ai_deployer_admin_bootstrap();

add_action('rest_api_init', 'shopagg_ai_deployer_register_routes');

add_filter('rest_post_dispatch', static function ($response, WP_REST_Server $server, WP_REST_Request $request) {
    if (!str_starts_with($request->get_route(), '/' . SHOPAGG_AI_DEPLOYER_REST_NS . '/')) {
        return $response;
    }
    if (!defined('DONOTCACHEPAGE')) {
        define('DONOTCACHEPAGE', true);
    }
    do_action('litespeed_control_set_nocache', 'SHOPAGG Deployer API');
    if (is_object($response) && method_exists($response, 'header')) {
        $response->header('Cache-Control', 'private, no-store, no-cache, must-revalidate, max-age=0');
        $response->header('Pragma', 'no-cache');
        $response->header('Expires', '0');
        $response->header('Vary', 'X-ShopAgg-AI-Deployer-Key');
        $response->header('X-LiteSpeed-Cache-Control', 'no-cache');
    }
    return $response;
}, 10, 3);

add_filter('plugin_action_links_' . plugin_basename(__FILE__), static function (array $links): array {
    array_unshift(
        $links,
        '<a href="' . esc_url(admin_url('admin.php?page=shopagg-ai-deployer')) . '">AI 提示词</a>',
        '<a href="' . esc_url(admin_url('admin.php?page=shopagg-ai-deployer-settings')) . '">连接与安全</a>'
    );
    return $links;
});
